<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

require_once 'WordDecorator.class.php';

/**
 * Description of TopLevelName
 *
 * @author rioultf
 */
//------------------------------------------------------------------------------
class Protocol extends WordDecoratorValue {

    static private $TYPE = 'PROTOCOL';

    function __construct($value) {
        parent::__construct(self::$TYPE, $value);
    }

    static public function match($value) {
        switch ($value) {
            case 'http':
            case 'https':
            case 'ftp':
            case 'ftps':
                return TRUE;
            default:
                return FALSE;
        }
    }

}

//------------------------------------------------------------------------------
class TopLevelDecorator extends WordDecoratorValue {

    static private $TYPE = 'TOP_LEVEL_NAME';

    function __construct($value) {
        parent::__construct(self::$TYPE, $value);
    }

    static public function match($value) {
        return isset(self::$countries[strtoupper($value)]);
    }

    public function toString() {
        return parent::toString() . '-' . self::$countries[$this->value];
    }

    static private $countries = array(
        'AD' => 'ANDORRA',
        'AERO' => 'AERO',
        'AE' => 'UNITED',
        'AF' => 'AFGHANISTAN',
        'AG' => 'ANTIGUA',
        'AI' => 'ANGUILLA',
        'AL' => 'ALBANIA',
        'AM' => 'ARMENIA',
        'AO' => 'ANGOLA',
        'AQ' => 'ANTARCTICA',
        'AR' => 'ARGENTINA',
        'ARPA' => 'ARPA',
        'AS' => 'AMERICAN',
        'ASIA' => 'ASIA',
        'AT' => 'AUSTRIA',
        'AU' => 'AUSTRALIA',
        'AW' => 'ARUBA',
        'AX' => 'ÅLAND',
        'AZ' => 'AZERBAIJAN',
        'BA' => 'BOSNIA',
        'BB' => 'BARBADOS',
        'BD' => 'BANGLADESH',
        'BE' => 'BELGIUM',
        'BF' => 'BURKINA',
        'BG' => 'BULGARIA',
        'BH' => 'BAHRAIN',
        'BI' => 'BURUNDI',
        'BIZ' => 'BIZ',
        'BJ' => 'BENIN',
        'BL' => 'SAINT',
        'BM' => 'BERMUDA',
        'BN' => 'BRUNEI',
        'BO' => 'BOLIVIA',
        'BQ' => 'BONAIRE',
        'BR' => 'BRAZIL',
        'BS' => 'BAHAMAS',
        'BT' => 'BHUTAN',
        'BV' => 'BOUVET',
        'BW' => 'BOTSWANA',
        'BY' => 'BELARUS',
        'BZ' => 'BELIZE',
        'CA' => 'CANADA',
        'CAT' => 'CAT',
        'CC' => 'COCOS',
        'CD' => 'CONGO',
        'CF' => 'CENTRAL',
        'CG' => 'CONGO',
        'CH' => 'SWITZERLAND',
        'CI' => 'CÔTE',
        'CK' => 'COOK',
        'CL' => 'CHILE',
        'CM' => 'CAMEROON',
        'CN' => 'CHINA',
        'CO' => 'COLOMBIA',
        'COM' => 'COM',
        'COOP' => 'COOP',
        'CR' => 'COSTA',
        'CU' => 'CUBA',
        'CV' => 'CAPE',
        'CW' => 'CURAÇAO',
        'CX' => 'CHRISTMAS',
        'CY' => 'CYPRUS',
        'CZ' => 'CZECH',
        'DE' => 'GERMANY',
        'DJ' => 'DJIBOUTI',
        'DK' => 'DENMARK',
        'DM' => 'DOMINICA',
        'DO' => 'DOMINICAN',
        'DZ' => 'ALGERIA',
        'EC' => 'ECUADOR',
        'EDU' => 'EDU',
        'EE' => 'ESTONIA',
        'EG' => 'EGYPT',
        'EH' => 'WESTERN',
        'ER' => 'ERITREA',
        'ES' => 'SPAIN',
        'ET' => 'ETHIOPIA',
        'FI' => 'FINLAND',
        'FJ' => 'FIJI',
        'FK' => 'FALKLAND',
        'FM' => 'MICRONESIA',
        'FO' => 'FAROE',
        'FR' => 'FRANCE',
        'GA' => 'GABON',
        'GB' => 'UNITED',
        'GD' => 'GRENADA',
        'GE' => 'GEORGIA',
        'GF' => 'FRENCH',
        'GG' => 'GUERNSEY',
        'GH' => 'GHANA',
        'GI' => 'GIBRALTAR',
        'GL' => 'GREENLAND',
        'GM' => 'GAMBIA',
        'GN' => 'GUINEA',
        'GOV' => 'GOV',
        'GP' => 'GUADELOUPE',
        'GQ' => 'EQUATORIAL',
        'GR' => 'GREECE',
        'GS' => 'SOUTH',
        'GT' => 'GUATEMALA',
        'GU' => 'GUAM',
        'GW' => 'GUINEA-BISSAU',
        'GY' => 'GUYANA',
        'HK' => 'HONG',
        'HM' => 'HEARD',
        'HN' => 'HONDURAS',
        'HR' => 'CROATIA',
        'HT' => 'HAITI',
        'HU' => 'HUNGARY',
        'ID' => 'INDONESIA',
        'IE' => 'IRELAND',
        'IL' => 'ISRAEL',
        'IM' => 'ISLE',
        'INFO' => 'INFO',
        'IN' => 'INDIA',
        'INT' => 'INT',
        'IO' => 'BRITISH',
        'IQ' => 'IRAQ',
        'IR' => 'IRAN',
        'IS' => 'ICELAND',
        'IT' => 'ITALY',
        'JE' => 'JERSEY',
        'JM' => 'JAMAICA',
        'JOBS' => 'JOBS',
        'JO' => 'JORDAN',
        'JP' => 'JAPAN',
        'KE' => 'KENYA',
        'KG' => 'KYRGYZSTAN',
        'KH' => 'CAMBODIA',
        'KI' => 'KIRIBATI',
        'KM' => 'COMOROS',
        'KN' => 'SAINT',
        'KP' => 'KOREA',
        'KR' => 'KOREA',
        'KW' => 'KUWAIT',
        'KY' => 'CAYMAN',
        'KZ' => 'KAZAKHSTAN',
        'LA' => 'LAO',
        'LB' => 'LEBANON',
        'LC' => 'SAINT',
        'LI' => 'LIECHTENSTEIN',
        'LK' => 'SRI',
        'LR' => 'LIBERIA',
        'LS' => 'LESOTHO',
        'LT' => 'LITHUANIA',
        'LU' => 'LUXEMBOURG',
        'LV' => 'LATVIA',
        'LY' => 'LIBYA',
        'MA' => 'MOROCCO',
        'MC' => 'MONACO',
        'MD' => 'MOLDOVA',
        'ME' => 'MONTENEGRO',
        'MF' => 'SAINT',
        'MG' => 'MADAGASCAR',
        'MH' => 'MARSHALL',
        'MIL' => 'MIL',
        'MK' => 'MACEDONIA',
        'ML' => 'MALI',
        'MM' => 'MYANMAR',
        'MN' => 'MONGOLIA',
        'MOBI' => 'MOBI',
        'MO' => 'MACAO',
        'MP' => 'NORTHERN',
        'MQ' => 'MARTINIQUE',
        'MR' => 'MAURITANIA',
        'MS' => 'MONTSERRAT',
        'MT' => 'MALTA',
        'MU' => 'MAURITIUS',
        'MUSEUM' => 'MUSEUM',
        'MV' => 'MALDIVES',
        'MW' => 'MALAWI',
        'MX' => 'MEXICO',
        'MY' => 'MALAYSIA',
        'MZ' => 'MOZAMBIQUE',
        'NAME' => 'NAME',
        'NA' => 'NAMIBIA',
        'NC' => 'NEW',
        'NE' => 'NIGER',
        'NET' => 'NET',
        'NF' => 'NORFOLK',
        'NG' => 'NIGERIA',
        'NI' => 'NICARAGUA',
        'NL' => 'NETHERLANDS',
        'NO' => 'NORWAY',
        'NP' => 'NEPAL',
        'NR' => 'NAURU',
        'NU' => 'NIUE',
        'NZ' => 'NEW',
        'OM' => 'OMAN',
        'ORG' => 'ORG',
        'PA' => 'PANAMA',
        'PE' => 'PERU',
        'PF' => 'FRENCH',
        'PG' => 'PAPUA',
        'PH' => 'PHILIPPINES',
        'PK' => 'PAKISTAN',
        'PL' => 'POLAND',
        'PM' => 'SAINT',
        'PN' => 'PITCAIRN',
        'POST' => 'POST',
        'PRO' => 'PRO',
        'PR' => 'PUERTO',
        'PS' => 'PALESTINIAN',
        'PT' => 'PORTUGAL',
        'PW' => 'PALAU',
        'PY' => 'PARAGUAY',
        'QA' => 'QATAR',
        'RE' => 'RÉUNION',
        'RO' => 'ROMANIA',
        'RS' => 'SERBIA',
        'RU' => 'RUSSIAN',
        'RW' => 'RWANDA',
        'SA' => 'SAUDI',
        'SB' => 'SOLOMON',
        'SC' => 'SEYCHELLES',
        'SD' => 'SUDAN',
        'SE' => 'SWEDEN',
        'SG' => 'SINGAPORE',
        'SH' => 'SAINT',
        'SI' => 'SLOVENIA',
        'SJ' => 'SVALBARD',
        'SK' => 'SLOVAKIA',
        'SL' => 'SIERRA',
        'SM' => 'SAN',
        'SN' => 'SENEGAL',
        'SO' => 'SOMALIA',
        'SR' => 'SURINAME',
        'SS' => 'SOUTH',
        'ST' => 'SAO',
        'SV' => 'EL',
        'SX' => 'SINT',
        'SY' => 'SYRIAN',
        'SZ' => 'SWAZILAND',
        'TC' => 'TURKS',
        'TD' => 'CHAD',
        'TEL' => 'TEL',
        'TF' => 'FRENCH',
        'TG' => 'TOGO',
        'TH' => 'THAILAND',
        'TJ' => 'TAJIKISTAN',
        'TK' => 'TOKELAU',
        'TL' => 'TIMOR-LESTE',
        'TM' => 'TURKMENISTAN',
        'TN' => 'TUNISIA',
        'TO' => 'TONGA',
        'TRAVEL' => 'TRAVEL',
        'TR' => 'TURKEY',
        'TT' => 'TRINIDAD',
        'TV' => 'TUVALU',
        'TW' => 'TAIWAN',
        'TZ' => 'TANZANIA',
        'UA' => 'UKRAINE',
        'UG' => 'UGANDA',
        'UM' => 'UNITED',
        'US' => 'UNITED',
        'UY' => 'URUGUAY',
        'UZ' => 'UZBEKISTAN',
        'VA' => 'HOLY',
        'VC' => 'SAINT',
        'VE' => 'VENEZUELA',
        'VG' => 'VIRGIN',
        'VI' => 'VIRGIN',
        'VN' => 'VIET',
        'VU' => 'VANUATU',
        'WF' => 'WALLIS',
        'WS' => 'SAMOA',
        'YE' => 'YEMEN',
        'YT' => 'MAYOTTE',
        'ZA' => 'SOUTH',
        'ZM' => 'ZAMBIA',
        'ZW' => 'ZIMBABWE');

}

?>
